version: '3.8'

services:
  mysql:
    image: mysql:8.0
    container_name: sveacms-db
    restart: always
    environment:
      MYSQL_DATABASE: sveacms
      MYSQL_USER: devuser
      MYSQL_PASSWORD: devpass
      MYSQL_ROOT_PASSWORD: rootpass
    ports:
      - "3307:3306"
    volumes:
      - mysql_data:/var/lib/mysql
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "localhost", "-p${MYSQL_ROOT_PASSWORD}"]
      interval: 10s
      timeout: 5s
      retries: 5

  sveacms-app:
    build: .
    container_name: sveacms-app
    restart: always
    ports:
      - "8080:8080"
    depends_on:
      mysql:
        condition: service_healthy
    environment:
      spring.datasource.url: jdbc:mysql://mysql:3306/sveacms?useSSL=false&allowPublicKeyRetrieval=true
      spring.datasource.username: devuser
      spring.datasource.password: devpass

volumes:
  mysql_data:
